import re

# Read app.js
with open('app.js', 'r', encoding='utf-8') as f:
    js = f.read()

# Define the new meetings code without using conflicting triple quotes
meetings_lines = [
    "window.startNewMeeting = async function(targetEmpId, targetEmpName, isGroup) {",
    "    var topic = isGroup ? \"اجتماع جماعي\" : `مكالمة فردية مع ${targetEmpName}`;",
    "    var roomName = \"TechGo_\" + Date.now() + \"_\" + Math.floor(Math.random()*1000);",
    "    ",
    "    try {",
    "        var meetingData = {",
    "            roomName: roomName,",
    "            topic: topic,",
    "            isGroup: isGroup,",
    "            createdBy: TG_USER.uid,",
    "            createdByName: TG_USER.displayName || TG_USER.name || \"مستخدم\",",
    "            createdAt: firebase.firestore.FieldValue.serverTimestamp(),",
    "            status: isGroup ? 'active' : 'calling'",
    "        };",
    "        ",
    "        if(!isGroup) {",
    "            meetingData.targetUid = targetEmpId;",
    "            meetingData.targetName = targetEmpName;",
    "        }",
    "        ",
    "        var meetingRef = await db.collection('meetings').add(meetingData);",
    "        _currentMeetingId = meetingRef.id;",
    "        ",
    "        if(!isGroup) {",
    "            window._callStatusUnsubscribe = db.collection('meetings').doc(_currentMeetingId).onSnapshot(function(doc) {",
    "                if(!doc.exists) return;",
    "                var d = doc.data();",
    "                var statusHeader = document.getElementById('callStatusHeaderAdmin') || document.getElementById('callStatusHeaderEmp');",
    "                ",
    "                if(d.status === 'rejected') {",
    "                    alert(\"تم رفض المكالمة من قبل الطرف الآخر.\");",
    "                    endCall();",
    "                } else if(d.status === 'active') {",
    "                    if(statusHeader) statusHeader.textContent = \"المكالمة نشطة الآن\";",
    "                } else if(d.status === 'ended') {",
    "                    endCall();",
    "                }",
    "            });",
    "        }",
    "        ",
    "        if(!isGroup) {",
    "            if(typeof tgSendPushToUser === 'function') {",
    "                tgSendPushToUser(targetEmpId, \"📞 مكالمة واردة\", `مكالمة واردة من ${meetingData.createdByName}. انضم الآن!`, 'livemeeting');",
    "            }",
    "        } else {",
    "            if(TG_USER.role === 'admin' || TG_USER.role === 'tech_admin') {",
    "                if(typeof tgBroadcastPush === 'function') {",
    "                    tgBroadcastPush('🎥 اجتماع مباشر', `يوجد اجتماع جماعي الآن: ${topic}. يرجى الانضمام.`, 'livemeeting', '');",
    "                }",
    "            }",
    "        }",
    "        ",
    "        startJitsiMeeting(roomName, topic, true);",
    "        ",
    "    } catch(e) {",
    "        console.error(\"Error creating meeting:\", e);",
    "        alert(\"حدث خطأ أثناء محاولة بدء الاجتماع. يرجى المحاولة مرة أخرى.\");",
    "    }",
    "};",
    "",
    "window.startJitsiMeeting = async function(roomName, subject, isCreator) {",
    "    var adminContainer = document.getElementById('jitsiAdminContainer');",
    "    var empContainer = document.getElementById('jitsiEmpContainer');",
    "    var wrapper = adminContainer || empContainer;",
    "    ",
    "    if(wrapper) {",
    "        wrapper.style.display = 'block';",
    "        var statusHeader = document.getElementById('callStatusHeaderAdmin') || document.getElementById('callStatusHeaderEmp');",
    "        if(statusHeader) {",
    "            statusHeader.textContent = isCreator ? \"جاري الاتصال...\" : \"المكالمة نشطة الآن\";",
    "        }",
    "    }",
    "    ",
    "    var displayName = TG_USER.displayName || TG_USER.name || \"مستخدم\";",
    "    var jitsiUrl = \"https://meet.jit.si/\" + roomName + \"#userInfo.displayName=\" + encodeURIComponent('\"' + displayName + '\"');",
    "    ",
    "    if(isCreator) {",
    "        jitsiUrl += \"&config.lobby.enabled=true\";",
    "    }",
    "    ",
    "    window._lastJitsiUrl = jitsiUrl;",
    "    window._jitsiWindow = window.open(jitsiUrl, \"_blank\");",
    "};",
    "",
    "window.reopenJitsiWindow = function() {",
    "    if(window._jitsiWindow && !window._jitsiWindow.closed) {",
    "        window._jitsiWindow.focus();",
    "    } else if(window._lastJitsiUrl) {",
    "        window._jitsiWindow = window.open(window._lastJitsiUrl, \"_blank\");",
    "    }",
    "};",
    "",
    "window.joinCall = async function(meetingId, roomName, topic, isCreator) {",
    "    _currentMeetingId = meetingId;",
    "    ",
    "    if(!isCreator && window.db) {",
    "        db.collection('meetings').doc(meetingId).update({",
    "            status: 'active'",
    "        }).catch(function(e){console.error(e)});",
    "    }",
    "    ",
    "    startJitsiMeeting(roomName, topic, isCreator);",
    "};",
    "",
    "window.endCall = async function() {",
    "    if(window._jitsiWindow && !window._jitsiWindow.closed) {",
    "        window._jitsiWindow.close();",
    "        window._jitsiWindow = null;",
    "    }",
    "    ",
    "    if(window._callStatusUnsubscribe) {",
    "        window._callStatusUnsubscribe();",
    "        window._callStatusUnsubscribe = null;",
    "    }",
    "    ",
    "    var adminContainer = document.getElementById('jitsiAdminContainer');",
    "    var empContainer = document.getElementById('jitsiEmpContainer');",
    "    ",
    "    if(adminContainer) adminContainer.style.display = 'none';",
    "    if(empContainer) empContainer.style.display = 'none';",
    "    ",
    "    if(_currentMeetingId && window.db) {",
    "        try {",
    "            await db.collection('meetings').doc(_currentMeetingId).update({",
    "                status: 'ended',",
    "                endedAt: firebase.firestore.FieldValue.serverTimestamp()",
    "            });",
    "        } catch(e) {",
    "            console.error(\"Error updating meeting status:\", e);",
    "        }",
    "        _currentMeetingId = null;",
    "    }",
    "};",
    "",
    "var _meetingListenerInit = false;",
    "window.initMeetingsListener = function() {",
    "    if(_meetingListenerInit || !window.db) return;",
    "    _meetingListenerInit = true;",
    "    ",
    "    db.collection('meetings').where('status', 'in', ['calling', 'active']).onSnapshot(function(snap) {",
    "        var adminList = document.getElementById('activeMeetingsListAdmin');",
    "        var empList = document.getElementById('activeMeetingsListEmp');",
    "        var listContainer = adminList || empList;",
    "        ",
    "        if(!listContainer) return;",
    "        ",
    "        var hasActive = false;",
    "        var html = '';",
    "        ",
    "        snap.forEach(function(doc) {",
    "            var data = doc.data();",
    "            ",
    "            var isCreator = data.createdBy === TG_USER.uid;",
    "            var isTarget = data.targetUid === TG_USER.uid;",
    "            var isGroup = data.isGroup;",
    "            var isAdmin = (TG_USER.role === 'admin' || TG_USER.role === 'tech_admin');",
    "            ",
    "            if(isCreator || isTarget || isGroup || isAdmin) {",
    "                hasActive = true;",
    "                ",
    "                var title = data.isGroup ? `اجتماع جماعي: ${data.topic || 'بدون عنوان'}` : `مكالمة فردية: ${data.topic || 'بدون عنوان'}`;",
    "                var subtitle = data.isGroup ? `بواسطة: ${data.createdByName}` : (isTarget ? `مكالمة من: ${data.createdByName}` : `مكالمة إلى: ${data.targetName}`);",
    "                var statusText = (data.status === 'calling') ? '📞 جاري الرنين...' : '🟢 مباشر الآن';",
    "                ",
    "                html += `<div style=\"background:var(--bg2); border:1px solid var(--ok); padding:15px; border-radius:8px; margin-bottom:10px; display:flex; justify-content:space-between; align-items:center; flex-wrap:wrap; gap:10px; border-left: 4px solid var(--ok);\">",
    "                    <div>",
    "                        <div style=\"font-weight:bold; color:var(--tx); font-size:15px;\"><span style=\"color:var(--ok); font-size:10px; margin-left:5px;\">${statusText}</span> ${title}</div>",
    "                        <div style=\"font-size:12px; color:var(--tx2);\">${subtitle}</div>",
    "                    </div>",
    "                    <button class=\"bt\" onclick=\"joinCall('${doc.id}', '${data.roomName}', '${data.topic || ''}', ${isCreator})\" style=\"background:var(--ok); color:#fff; font-size:13px;\"><i class=\"fa fa-sign-in\"></i> انضمام للمكالمة</button>",
    "                </div>`;",
    "                ",
    "                if(isTarget && !isCreator && data.status === 'calling' && typeof playMeetingRinging === 'function' && !window._declinedMeeting) {",
    "                     var modal = document.getElementById('incomingMeetingModal');",
    "                     if(modal && modal.style.display !== 'flex') {",
    "                         modal.style.display = 'flex';",
    "                         playMeetingRinging(data.createdByName, doc.id, data.roomName, data.topic);",
    "                     }",
    "                }",
    "            }",
    "        });",
    "        ",
    "        if(!hasActive) {",
    "            listContainer.innerHTML = '<div style=\"color:var(--tx2); padding:10px; background:var(--bg2); border-radius:8px; text-align:center; font-size:13px;\">لا توجد اجتماعات أو مكالمات نشطة حالياً.</div>';",
    "        } else {",
    "            listContainer.innerHTML = html;",
    "        }",
    "    });",
    "};"
]

new_meetings_logic = "\\n".join(meetings_lines) + "\\n"

# Replace meetings block in app.js
start_idx = js.find('window.startNewMeeting = async function')
if start_idx != -1:
    js = js[:start_idx] + new_meetings_logic
    print("app.js updated successfully!")
else:
    print("Could not find startNewMeeting in app.js")

with open('app.js', 'w', encoding='utf-8') as f:
    f.write(js)
